#!/usr/bin/env bash
set -euo pipefail

# Run one verified circular-injection fixture through the public ALDERAAN path.
# This script is deliberately separate from production batch runners. It does
# not download files and it never writes into a canonical results directory.

TARGET="${1:?KOI target required}"
KEPID="${2:?KIC identifier required}"
FIXTURE_DIR="${FIXTURE_DIR:?fixture directory required}"
PROJECT_DIR="${PROJECT_DIR:?isolated project directory required}"
READER_AUDIT="${READER_AUDIT:-}"
HILDALE_DIAGNOSTIC_SEED="${HILDALE_DIAGNOSTIC_SEED:-}"
RUN_ID="${RUN_ID:-diagnostic_circular}"
ALDERAAN_REPO="${ALDERAAN_REPO:-$HOME/alderaan_sagear_pinned}"
MISSION="${MISSION:-Kepler}"
FIXTURE_MANIFEST="$FIXTURE_DIR/diagnostic_fixture_manifest.json"
HOLCZER_SOURCE="$ALDERAAN_REPO/Catalogs/holczer_2016_kepler_ttvs.txt"

export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-1}"
export PYTHONPATH="$ALDERAAN_REPO${PYTHONPATH:+:$PYTHONPATH}"

for required in \
  "$FIXTURE_MANIFEST" \
  "$FIXTURE_DIR/diagnostic_catalog.csv" \
  "$HOLCZER_SOURCE" \
  "$ALDERAAN_REPO/bin/detrend_and_estimate_ttvs.py" \
  "$ALDERAAN_REPO/bin/analyze_autocorrelated_noise.py" \
  "$ALDERAAN_REPO/bin/fit_transit_shape_simultaneous_nested.py"
do
  [ -s "$required" ] || { echo "Missing required fixture or ALDERAAN file: $required" >&2; exit 2; }
done

[ -n "$READER_AUDIT" ] || { echo "READER_AUDIT JSON path is required" >&2; exit 2; }
[ -s "$READER_AUDIT" ] || { echo "Reader audit is missing or empty: $READER_AUDIT" >&2; exit 2; }
[ -n "$HILDALE_DIAGNOSTIC_SEED" ] || { echo "HILDALE_DIAGNOSTIC_SEED is required" >&2; exit 2; }
[[ "$HILDALE_DIAGNOSTIC_SEED" =~ ^[0-9]+$ ]] || {
  echo "HILDALE_DIAGNOSTIC_SEED must be a nonnegative integer" >&2
  exit 2
}

# The pinned nested-sampling driver reads this variable to construct Dynesty's
# Generator. Keep it tied to the diagnostic seed used by the stage wrapper.
export ALDERAAN_SEED="$HILDALE_DIAGNOSTIC_SEED"

# The audit is generated by the pinned ALDERAAN reader. Validate its identity
# before creating a project or allowing any fitting stage to start.
python - "$READER_AUDIT" "$FIXTURE_MANIFEST" <<'PY'
import hashlib
import json
from pathlib import Path
import sys


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def stop(message):
    raise SystemExit("Reader audit rejected: " + message)


audit_path = Path(sys.argv[1])
manifest_path = Path(sys.argv[2])
try:
    audit = json.loads(audit_path.read_text(encoding="utf-8"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
except (OSError, json.JSONDecodeError) as error:
    stop("invalid JSON: " + str(error))
if not isinstance(audit, dict) or audit.get("pass") is not True:
    stop("pass must be true")
if audit.get("fixture_manifest_sha256") != sha256(manifest_path):
    stop("fixture manifest SHA-256 mismatch")
fixture_injection = manifest.get("injection", {}).get("sha256")
audit_injection = audit.get("injection_sha256")
if fixture_injection is not None or audit_injection is not None:
    if not isinstance(fixture_injection, str) or not fixture_injection:
        stop("fixture lacks the injection SHA-256 named by the audit")
    if audit_injection != fixture_injection:
        stop("injection SHA-256 mismatch")
PY

if [ -e "$PROJECT_DIR" ]; then
  echo "Refusing to reuse an existing diagnostic project: $PROJECT_DIR" >&2
  exit 2
fi

mkdir -p "$PROJECT_DIR/Catalogs" "$PROJECT_DIR/Results" "$PROJECT_DIR/Figures" "$PROJECT_DIR/status"
cp -a "$FIXTURE_DIR/Data" "$PROJECT_DIR/Data"
cp "$FIXTURE_DIR/diagnostic_catalog.csv" "$PROJECT_DIR/Catalogs/diagnostic_catalog.csv"
cp "$FIXTURE_MANIFEST" "$PROJECT_DIR/fixture_manifest.json"
cp "$READER_AUDIT" "$PROJECT_DIR/reader_audit.json"

# Launch every stage in a fresh Python process with the same explicit seed.
# This leaves the pinned ALDERAAN checkout unchanged while covering its use of
# NumPy's process-global legacy random generator during detrending.
SEEDED_STAGE_WRAPPER="$PROJECT_DIR/run_seeded_stage.py"
cat > "$SEEDED_STAGE_WRAPPER" <<'PY'
import runpy
import sys

import numpy as np


seed = int(sys.argv[1])
script = sys.argv[2]
np.random.seed(seed)
sys.argv = [script, *sys.argv[3:]]
runpy.run_path(script, run_name="__main__")
PY

run_seeded_stage() {
  python "$SEEDED_STAGE_WRAPPER" "$HILDALE_DIAGNOSTIC_SEED" "$@"
}

# Remove this synthetic system from a project-local timing catalog. Historical
# Holczer timings would otherwise replace the phase-shifted injected ephemeris.
HOLCZER_LOCAL="$PROJECT_DIR/Catalogs/holczer_2016_kepler_ttvs.txt"
HOLCZER_REMOVED="$(python - "$HOLCZER_SOURCE" "$HOLCZER_LOCAL" "$TARGET" <<'PY'
import hashlib
from pathlib import Path
import re
import sys


source = Path(sys.argv[1])
destination = Path(sys.argv[2])
target = sys.argv[3]
match = re.fullmatch(r"K(\d+)", target)
if match is None:
    raise SystemExit("Target must have the form K followed by digits")
target_number = int(match.group(1))
source_bytes = source.read_bytes()
source_sha256 = hashlib.sha256(source_bytes).hexdigest()
lines = source_bytes.decode("utf-8").splitlines(keepends=True)
kept = []
removed = 0
unrelated = 0
for line in lines:
    stripped = line.lstrip()
    if not stripped or stripped.startswith("#"):
        kept.append(line)
        continue
    fields = stripped.split()
    try:
        koi_system = int(float(fields[0]))
    except (IndexError, ValueError):
        raise SystemExit("Unrecognized Holczer data row: " + line.rstrip())
    if koi_system == target_number:
        removed += 1
    else:
        unrelated += 1
        kept.append(line)
if unrelated == 0:
    raise SystemExit("Filtered Holczer catalog contains no unrelated data rows")
provenance = (
    "# HILDALE_DIAGNOSTIC_FILTER "
    f"target={target} removed_rows={removed} source_sha256={source_sha256}\n"
)
with destination.open("w", encoding="utf-8", newline="\n") as handle:
    handle.write(provenance)
    handle.writelines(kept)
print(removed)
PY
)"

LC_COUNT="$(find "$PROJECT_DIR/Data" -maxdepth 1 -type f -name "kplr$(printf '%09d' "$KEPID")-*_llc.fits" | wc -l)"
[ "$LC_COUNT" -gt 0 ] || { echo "Fixture contains no long-cadence FITS for KIC $KEPID" >&2; exit 2; }

RESULT="$PROJECT_DIR/Results/$RUN_ID/$TARGET/$TARGET-results.fits"
echo "running" > "$PROJECT_DIR/status/$TARGET.status"
pushd "$ALDERAAN_REPO" >/dev/null
run_seeded_stage bin/detrend_and_estimate_ttvs.py --mission "$MISSION" --target "$TARGET" --run_id "$RUN_ID" --project_dir "$PROJECT_DIR" --data_dir "$PROJECT_DIR/Data/" --catalog diagnostic_catalog.csv
run_seeded_stage bin/analyze_autocorrelated_noise.py --mission "$MISSION" --target "$TARGET" --run_id "$RUN_ID" --project_dir "$PROJECT_DIR" --data_dir "$PROJECT_DIR/Data/" --catalog diagnostic_catalog.csv
run_seeded_stage bin/fit_transit_shape_simultaneous_nested.py --mission "$MISSION" --target "$TARGET" --run_id "$RUN_ID" --project_dir "$PROJECT_DIR"
popd >/dev/null

[ -s "$RESULT" ] || { echo "ALDERAAN finished without a result FITS" >&2; echo "missing_results" > "$PROJECT_DIR/status/$TARGET.status"; exit 3; }
sha256sum "$PROJECT_DIR/fixture_manifest.json" "$PROJECT_DIR/reader_audit.json" "$HOLCZER_SOURCE" "$HOLCZER_LOCAL" "$RESULT" > "$PROJECT_DIR/provenance_sha256.txt"
printf 'target\t%s\nrun_id\t%s\nkic\t%s\nalderaan_commit\t%s\ndiagnostic_seed\t%s\nalderaan_seed\t%s\nlong_cadence_files\t%s\nholczer_removed_rows\t%s\n' \
  "$TARGET" "$RUN_ID" "$KEPID" "$(git -C "$ALDERAAN_REPO" rev-parse HEAD)" "$HILDALE_DIAGNOSTIC_SEED" "$ALDERAAN_SEED" "$LC_COUNT" "$HOLCZER_REMOVED" \
  > "$PROJECT_DIR/run_provenance.tsv"
echo "complete" > "$PROJECT_DIR/status/$TARGET.status"
echo "$RESULT"
