from __future__ import annotations

import re

import check_professor_release as release


def test_release_surface_has_no_forbidden_markers() -> None:
    assert release.scan() == []


def test_release_check_rejects_ai_assistant_markers() -> None:
    pattern = release.FORBIDDEN["AI assistant marker"]
    assert pattern.search("This was generated by " + "Chat" + "GPT")
    assert pattern.search("As an " + "AI" + ", I cannot verify the result")
    assert pattern.search("Clau" + "de review handoff")
    assert not pattern.search("The ALDERAAN analysis is incomplete")


def test_private_record_names_are_case_insensitive() -> None:
    private_names = {"report_hildale.md", "recovery_live_checkpoint.md"}
    assert "report_hildale.md" in private_names
    assert re.fullmatch(r"report_hildale\.md", "report_hildale.md")
